### ISSUE TITLE
think through how to handle prompt_toolkit related settings

### ISSUE THREAD

**Issue by ivanov** [ipython/rlipython#13]
for example - if someone has prompt toolkit settings for PT's vi mode, but their inputrc does not enable vi mode, should we enable vi mode or not?

**Comment by Carreau** [comment]
I think we can ignore prompt_toolkit customizations, or we'll be a in rats nest as PTK may move to understand .inputrc

**Comment by ivanov** [comment]
Yeah, I think that makes sense. One thing we could do is give a message about that at `rlipython.install()` time letting the user know we don't support such settings if they have any of them set (and say which ones we do support, as well as mentioning `.inputrc`).

**Comment by heroxbd** [comment]
Just ignore any `prompt_toolkit`, the users who revert to good old readline knows what they are doing.

**Comment by ivanov** [comment]
Ok, I will add some code that will just ignore `editing_mode` and `display_completions` settings for users who happen to set those, that way they don't get a 

```
[TerminalIpythonApp] WARNING: Config option`editing_mode` not recognized by `TerminalInteractiveShell`.
```

after enabling `rlipython`

**Comment by ivanov** [comment]
Another thing I briefly considered was to rename the TerminalInteractiveShell class to something else, which would then not issue such warnings, but it would also prevent us from tapping into other settings which I think we want to to respect-  such as `editor` and `pager` - since we don't want to force users to add new entries for those again.
