### ISSUE TITLE
PyPI version is broken

### ISSUE THREAD

**Issue by yamad** [ipython/rlipython#14]
The `pip`-installed version of `rlipython` errors out because it can't find the module `IPython.utils.rlineimpl`. This appears to be fixed by https://github.com/ipython/rlipython/pull/1 . Probably makes sense to push the fixed version to pypi?

**Comment by Carreau** [comment]
Yes ! Thanks ! We'll do that soon.

**Comment by ivanov** [comment]
I just released version 0.1.0 on PyPI - hope you enjoy it, @yamad.
